
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DELETE FROM GT ID INSERT INTO NUMBER SELECT SET STRING UPDATE VALUES WHEREstatement : SELECT ID FROM ID WHERE expressionstatement : INSERT INTO ID VALUES expressionstatement : UPDATE ID SET ID VALUES expressionstatement : DELETE FROM ID WHERE expressionexpression : ID\n                  | NUMBER\n                  | STRING'
    
_lr_action_items = {'SELECT':([0,],[2,]),'INSERT':([0,],[3,]),'UPDATE':([0,],[4,]),'DELETE':([0,],[5,]),'$end':([1,19,20,21,22,24,25,26,],[0,-5,-2,-6,-7,-4,-1,-3,]),'ID':([2,4,7,9,10,12,15,17,18,23,],[6,8,11,13,14,16,19,19,19,19,]),'INTO':([3,],[7,]),'FROM':([5,6,],[9,10,]),'SET':([8,],[12,]),'VALUES':([11,16,],[15,23,]),'WHERE':([13,14,],[17,18,]),'NUMBER':([15,17,18,23,],[21,21,21,21,]),'STRING':([15,17,18,23,],[22,22,22,22,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([15,17,18,23,],[20,24,25,26,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> SELECT ID FROM ID WHERE expression','statement',6,'p_statement_select','parser.py',5),
  ('statement -> INSERT INTO ID VALUES expression','statement',5,'p_statement_insert','parser.py',9),
  ('statement -> UPDATE ID SET ID VALUES expression','statement',6,'p_statement_update','parser.py',13),
  ('statement -> DELETE FROM ID WHERE expression','statement',5,'p_statement_delete','parser.py',17),
  ('expression -> ID','expression',1,'p_expression','parser.py',21),
  ('expression -> NUMBER','expression',1,'p_expression','parser.py',22),
  ('expression -> STRING','expression',1,'p_expression','parser.py',23),
]
